<?php
return array(
    '首页'  =>   'Home',
    '通知公告'  =>   'Notices',
    '热点新闻'  =>   'Latest news',
    '了解更多'  =>   'More',
    '现任领导'  =>   'Current presidents',
    '代表性项目'  =>   'Representative programs',
    '相关新闻'  =>   'Relevant news',
    '论文'  =>   'Papers',
    '上一页'  =>   'Previous',
    '下一页'  =>   'Next',
    '深港脑科学创新研究院荣获'  =>   'The honour of Shenzhen - Hong Kong Institute of Brain Science',
    '获奖'  =>   'Awards',  
    '人才招聘'  =>   'Join us',    
    '研究中心'  =>   'Affiliated institutes',
    '课题组'  =>   'Research groups',
    '重点实验室'  =>   'Flagship labs',
    '科研支撑'  =>   'Support for researches',
    '本科学重点实验室人员结构'  =>   'Staff structure of labs',
    '学术委员会成员'  =>   'Academic committee members',
    '导师介绍'  =>   'Our academic staff',
    '新闻动态'  =>   'News',
    '会议预告'  =>   'Upcoming conferences',
    '时间'  =>   'Timetable: ',
    '地点'  =>   'Address:',
    '主持'  =>   'Host: ',
    '通知公告'  =>   'Notices',
    '视频'  =>   'Videos',
    '作者'  =>   'Author: ',
    '搜索'  =>   'Search',
    '友情链接'  =>   'Quick links',
    '搜索提示'  =>   'Search for ...',
    '搜索结果'  =>   'Find <strong> %s </strong> matching records.',
);